import {NeighborhoodRenderer,drawPortrait} from './renderer.js';
import {psychologyMarkup,relationshipsMarkup,routineMarkup,householdMarkup} from './life-ui.js';
import {affectMarkup,possessionsMarkup,portraitUrl,openRelationships,closeRelationships} from './story-ui.js';
import {createObjectExplorer} from './object-explorer.js';

const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=name=>`<svg class="icon"><use href="#i-${name}"/></svg>`;
const timeLabel=t=>`${String(Math.floor(t/3600)%24).padStart(2,'0')}:${String(Math.floor(t/60)%60).padStart(2,'0')}`;
const pretty=k=>k.replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());
const percent=n=>Math.round(n*100);
const needLabels={hunger:'Food',thirst:'Hydration',bladder:'Bladder',fatigue:'Energy',hygiene:'Hygiene',social:'Connection',fun:'Fun',comfort:'Comfort'};
const isCapture=new URLSearchParams(location.search).has('capture');
let world,state,renderer,person,rules,selected='resident_001',tab='overview',beats=[],personalBeats=[],connected=false,toastTimer,lastRenderedKey;
let objectExplorer;

async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){let message=`Request failed (${r.status})`;try{message=(await r.json()).detail||message}catch{}throw new Error(message)}return r.json()}
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),4000)}
function renderWorldIdentity(){const plan=world.planning_metadata||{},name=plan.name||world.name||'Mosswood';$('brand-world-name').textContent=name;$('world-headline').textContent=`Life in ${name}`;$('home-count').textContent=world.households.length;$('layout-label').textContent=plan.layout_id?'Living neighborhood':'Neighborhood 01';document.title=`${name} · A living neighborhood`}
async function control(body){try{updateState(await api('/api/control',body))}catch(e){toast(e.message)}}
function updateState(s){state=s;renderer?.setState(s);$('world-time').textContent=s.time;$('world-day').textContent=`${['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY','SATURDAY','SUNDAY'][(s.day-1)%7]} · DAY ${s.day}`;$('weather').textContent=`${s.environment.temperature_c}° · ${s.environment.weather}`;$('resident-count').textContent=s.population;
  $('pause').innerHTML=icon(s.paused?'play':'pause');$('pause').setAttribute('aria-label',s.paused?'Resume simulation':'Pause simulation');document.querySelectorAll('.speed').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===s.speed));
  $('speed-select').value=String(s.speed);
  $('world-status').textContent=`${s.population} lives unfolding · ${percent(s.wellbeing)}% wellbeing`;
  $('connection').textContent=s.fault?'Simulation paused: '+s.fault:!connected?'Reconnecting…':s.paused?'The world is paused':`Life goes on · ${s.speed}× speed`;
  $('performance').textContent=`${renderer?.fps||60} fps · 1 tile = 1 meter`;
}
function connect(){const socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);socket.onopen=()=>{connected=true};socket.onmessage=e=>updateState(JSON.parse(e.data));socket.onclose=()=>{connected=false;if(state){renderer.setState({...state,paused:true});$('connection').textContent='Connection lost · reconnecting…'}setTimeout(connect,1500)};socket.onerror=()=>socket.close()}

async function selectPerson(id,focus=false){objectExplorer?.close();selected=id;renderer.selected=id;renderer.openBuilding=null;if(focus)renderer.focusActor(id);await loadPerson();renderPeople()}
async function loadPerson(){const requested=selected;try{const data=await api('/api/actors/'+requested);if(requested!==selected)return;person=data;renderHeading();if(tab==='journal'){const j=await api('/api/actors/'+requested+'/journal?limit=45');if(requested!==selected)return;personalBeats=j.beats}renderInspector()}catch(e){if(!isCapture)toast(e.message)}}
function renderHeading(){const p=person;const household=world.households.find(h=>h.id===p.household_id);$('person-name').textContent=p.name;$('person-description').textContent=`${p.age} · ${p.profile.job}`;$('mood').textContent=p.affect?.states?.[0]?.label_de||p.emotion?.type||'Unbestimmt';$('person-traits').innerHTML=p.profile.traits.map(t=>`<span>${esc(t)}</span>`).join('');$('inspector-source').textContent=`${household.address} · State v${p.version}`;
  const canvas=$('portrait'),c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.imageSmoothingEnabled=false;c.fillStyle='#e9eddd';c.fillRect(0,0,canvas.width,canvas.height);c.fillStyle='#dee5cd';c.fillRect(0,canvas.height*.76,canvas.width,canvas.height*.24);c.fillStyle='#f0f2e6';c.fillRect(9,13,3,3);c.fillRect(canvas.width-15,28,2,2);drawPortrait(c,p.appearance,canvas.width/2,canvas.height+3,{scale:3.6,emotion:p.affect?.states?.length?p.affect.states:p.emotion?.type});
  $('follow').classList.toggle('active',renderer.follow);
}
function actionCard(p){const a=p.action;if(!a)return `<div class="doing-card"><div class="eyebrow">A MOMENT BETWEEN THINGS</div><h3>Considering what comes next</h3><p>The next decision will use current needs, available objects, and commitments.</p></div>`;
  const progress=Math.max(0,Math.min(1,(p.clock-a.started_at)/(a.ends_at-a.started_at)));const target=world.objects.find(o=>o.id===a.target_id);const location=target?.building_id?world.buildings.find(b=>b.id===target.building_id)?.name:target?.name;
  return `<div class="doing-card"><div class="eyebrow"><span class="tiny-dot"></span> ${a.phase==='travel'?'ON THE WAY':'RIGHT NOW'}</div><h3>${esc(a.phase==='travel'?'Heading to '+(target?.name?.toLowerCase()||'the park'):a.label)}</h3><p>${esc(a.reason)}.</p><p style="margin-top:5px">${esc(location||'With a neighbor')} <span style="float:right">Until ${timeLabel(a.ends_at)}</span></p><div class="progress-track"><span style="width:${progress*100}%"></span></div></div>`
}
function needsMarkup(p){return `<div class="section-heading">Feeling at home <span class="subtle">NEEDS</span></div><div class="needs">${Object.entries(p.needs).map(([name,value])=>{const sat=1-value,color=sat<.2?'#cb9476':sat<.4?'#c5b07a':'#a9bd8c';return `<div class="need-row" title="${esc(pretty(name))} urgency: ${percent(value)}%; rate: ${(p.need_rates[name]*3600).toFixed(3)} per world hour"><span class="need-label">${needLabels[name]}</span><div class="need-track" role="meter" aria-label="${needLabels[name]} satisfaction" aria-valuenow="${percent(sat)}" aria-valuemin="0" aria-valuemax="100"><span style="width:${sat*100}%;background:${color}"></span></div><span class="need-value">${percent(sat)}</span></div>`}).join('')}</div><p class="needs-note">Fuller bars mean more satisfied. Needs change with world time.</p>`}
function thoughtMarkup(p){return `<div class="thought-card"><div class="eyebrow">ON THEIR MIND</div><blockquote>“${esc(p.thought.text)}”</blockquote><small>Since ${timeLabel(p.thought.since)} · ${esc(p.thought.trigger.replaceAll('_',' '))}</small></div>`}
function goalsMarkup(p){return `<div class="section-heading">Little things to work toward <span class="subtle">GOALS</span></div>${p.goals.map(g=>`<div class="goal-item"><span class="goal-ring ${g.progress>=1?'done':''}"></span><div style="flex:1"><h4>${esc(g.title)}</h4><p>${g.kind==='ongoing'?'Ongoing wellbeing':g.progress>=1?'Completed today':`${percent(g.progress)}% of today's goal`}</p><div class="progress-track"><span style="width:${g.progress*100}%"></span></div></div></div>`).join('')}`}
function entryMarkup(b){return `<article class="journal-entry"><time>DAY ${Math.floor(b.interval[1]/86400)+1} · ${timeLabel(b.interval[1])}</time><p>${esc(b.narration)}</p><details><summary>${esc(b.rule_id)} · ${b.changes.length} changes</summary><code>${esc(b.id)}<br>Causes: ${esc(b.reasons.join('; ')||'World initialization')}<br>Previous: ${esc(b.causal_parent_ids.join(', ')||'None')}<br>Rule ${esc(b.model_and_rule_versions.version)} · Epoch ${b.owner_epoch}</code></details></article>`}
function detailsList(items){return `<dl class="detail-list">${items.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl>`}
function innerLife(p){const emotion=p.emotion||{};return `${affectMarkup(p)}${thoughtMarkup(p)}${psychologyMarkup(p,state)}<section class="detail-block"><h3>Bisherige Emotionsanzeige</h3><div class="emotion-bands"><div><b>${esc(emotion.type||'–')}</b><span>Anzeige</span></div><div><b>${percent(emotion.valence||0)}%</b><span>Valenz</span></div><div><b>${percent(emotion.arousal||0)}%</b><span>Aktivierung</span></div></div><p>Diese ältere Kurzansicht ist nicht die vollständige belegte Gefühlslage.</p></section>
  <section class="detail-block"><h3>Intentions & possibilities</h3>${p.intentions.map(i=>`<div class="intent"><b>${esc(i.text)}</b><p>${esc(i.status)}${i.prerequisites?' · '+esc(i.prerequisites.join(' → ')):''}</p></div>`).join('')}</section>
  ${relationshipsMarkup(p,state)}
  <section class="detail-block"><h3>What they believe</h3>${p.beliefs.slice(-5).reverse().map(b=>`<div class="belief"><p>${esc(b.proposition)}</p><small>${esc(b.confidence)} confidence · ${timeLabel(b.valid_from)}<br>Evidence: ${esc(b.evidence.join(', '))}</small></div>`).join('')}</section>
  <section class="detail-block"><h3>Remembered moments</h3>${p.memories.slice(-5).reverse().map(m=>`<div class="belief"><p>${esc(m.content)}</p><small>${timeLabel(m.at)} · ${esc(m.retention)} · ${esc(m.source_percepts.join(', '))}</small></div>`).join('')||'<p>No new experiences encoded yet.</p>'}</section>
  <p class="coverage-note">These are explicit fictional game states. First-order social estimates are uncertain and evidence-linked, not access to another mind. Verbatim dialogue and recursive higher-order beliefs remain unmodeled.</p>`}
function detailsMarkup(p){const action=p.action,target=world.objects.find(o=>o.id===action?.target_id),decision=p.last_decision,home=world.buildings.find(b=>b.id===p.home_id);return `${possessionsMarkup(p,world)}${home?.plan_variant?`<section class="detail-block"><h3>Wohnungsgrundriss</h3>${detailsList([['Variante',home.plan_variant],['Räume',(home.rooms||[]).map(id=>world.regions.find(r=>r.id===id)?.name||id).join(' · ')],['Eingang',home.frontage?.join(', ')||home.door?.join(', ')||'–']])}</section>`:''}<section class="detail-block"><h3>Here, now</h3>${detailsList([['Resident ID',p.id],['Location',p.locations.at(-1)?.name||'Neighborhood'],['Position',`${p.position[0]}, ${p.position[1]} m`],['Personal funds',`${p.money} coins`],['Inventory',Object.entries(p.inventory).map(([k,v])=>`${v} ${k.replaceAll('_',' ')}`).join(', ')],['Decision owner',`${p.owner} · epoch ${p.owner_epoch}`],['Last accepted Beat',p.last_beat||'Initialization']])}</section>
  <section class="detail-block"><h3>Work & skills</h3>${detailsList([['Arbeitsplatz',world.buildings.find(b=>b.id===p.workplace?.building_id)?.name||'Nicht zugewiesen'],['Arbeitsmodell',p.workplace?.work_from_home?'Homeoffice':'Arbeitsweg zum zugewiesenen Gebäude'],['Work hours',`${timeLabel(p.schedule.start)}–${timeLabel(p.schedule.end)}`],['Work completed',`${Math.round(p.schedule.work_seconds/60)} / ${p.schedule.work_target_seconds/60} min`],...Object.entries(p.skills).map(([k,v])=>[pretty(k),`${percent(v)} / 100`])])}</section>
  ${householdMarkup(p)}
  ${target?`<section class="detail-block"><h3>Current object & reservation</h3>${detailsList([['Object',target.name],['Footprint',`${target.w} × ${target.h} m · one object`],['Object ID',target.id],['Action phase',action.phase],['Reserved slot',action.reservation_id||'None'],['Capacity',target.capacity],['Condition',`${percent(state.resources.find(r=>r.id===target.id)?.condition??target.condition)}%`],['Action ends',timeLabel(action.ends_at)]])}</section>`:''}
  <section class="detail-block"><h3>Why this decision?</h3>${decision?`<p>At ${timeLabel(decision.at)}: ${esc(decision.policy)}. Draw: ${decision.random_draw===null?'External intent':decision.random_draw.toFixed(5)}.</p><table class="diagnostic-table"><thead><tr><th>Alternative</th><th>Utility</th></tr></thead><tbody>${decision.candidates.map(c=>`<tr title="${esc(JSON.stringify(c.terms))}"><td>${c.kind===decision.chosen?'↳ ':''}${esc(pretty(c.kind))}</td><td>${c.score.toFixed(3)}</td></tr>`).join('')}</tbody></table>${decision.rejected.map(r=>`<p>${esc(pretty(r.kind))}: ${esc(r.reason)}.</p>`).join('')}`:'<p>No utility decision recorded yet.</p>'}</section>
  <section class="detail-block"><h3>Individual preferences</h3>${detailsList(Object.entries(p.preferences).map(([k,v])=>[pretty(k),`${percent(v)}%`]))}</section>
  <section class="detail-block"><h3>Model coverage</h3>${detailsList(Object.entries(p.coverage).map(([k,v])=>[pretty(k),v]))}</section>
  <details id="raw-state"><summary style="font-size:10px;cursor:pointer;color:#748c62">All represented state · JSON</summary><pre class="raw-data">${esc(JSON.stringify(p,null,2))}</pre></details><div style="display:flex;gap:8px;margin-top:15px"><button id="export-person" class="small-button">Export state</button><a class="small-button" href="/api/bridge/${p.id}/context" target="_blank" rel="noreferrer" style="text-decoration:none">Agent context ↗</a></div>`}
function renderInspector(){if(!person)return;const key=`${selected}:${tab}:${person.version}`;if(tab!=='overview'&&lastRenderedKey===key)return;lastRenderedKey=key;const content=$('inspector-content'),scroll=content.scrollTop;const rawWasOpen=$('raw-state')?.open;const expanded=[...content.querySelectorAll('.journal-entry details[open]')].map(d=>d.parentElement.querySelector('time').textContent);
  if(tab==='overview')content.innerHTML=actionCard(person)+affectMarkup(person,{compact:true})+needsMarkup(person)+routineMarkup(person)+thoughtMarkup(person)+goalsMarkup(person);
  else if(tab==='mind')content.innerHTML=innerLife(person);
  else if(tab==='journal')content.innerHTML=`<div class="section-heading">A day in their life <span class="subtle">ACCEPTED EVENTS</span></div><p class="empty-note" style="margin-top:0;margin-bottom:20px">The choices, journeys, and little consequences that brought them here.</p>${personalBeats.map(entryMarkup).join('')||'<p class="empty-note">Their story is just beginning.</p>'}<button id="export-journal" class="small-button">Export these entries</button>`;
  else content.innerHTML=detailsMarkup(person);
  content.scrollTop=scroll;if(rawWasOpen&&$('raw-state'))$('raw-state').open=true;content.querySelectorAll('.journal-entry details').forEach(d=>{if(expanded.includes(d.parentElement.querySelector('time').textContent))d.open=true});
  $('export-person')?.addEventListener('click',()=>download(`${person.id}.json`,JSON.stringify(person,null,2),'application/json'));
  $('export-journal')?.addEventListener('click',()=>download(`${person.id}-journal.json`,JSON.stringify(personalBeats,null,2),'application/json'));
  content.querySelectorAll('[data-related-person]').forEach(b=>b.onclick=()=>selectPerson(b.dataset.relatedPerson,true));
}
async function setTab(name){tab=name;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-selected',String(b.dataset.tab===name))});$('inspector-content').scrollTop=0;await loadPerson()}
async function loadEvents(){try{beats=(await api('/api/beats?limit=60')).beats.filter(b=>b.rule_id!=='initialization');renderEvents()}catch{}}
function renderEvents(){const seen=new Set();const cards=beats.filter(b=>{const id=b.participants[0];if(!id||seen.has(id))return false;seen.add(id);return true}).slice(0,3);$('event-cards').innerHTML=cards.map(b=>{const a=state.actors.find(a=>a.id===b.participants[0]);return `<button class="event-card" data-resident="${esc(a?.id||selected)}"><span class="event-initial">${esc(a?.name?.[0]||'M')}</span><span class="event-copy"><h3>${esc(a?.name||'Mosswood')}</h3><p>${esc(b.narration.replace((a?.name||'')+' ',''))}</p><time>${timeLabel(b.interval[1])} · ${b.rule_id.startsWith('social')?'A shared moment':b.rule_id.startsWith('decision')?'A little intention':'Everyday life'}</time></span></button>`}).join('')||'<p class="empty-note">The neighborhood is waking up…</p>';document.querySelectorAll('[data-resident]').forEach(b=>b.onclick=()=>selectPerson(b.dataset.resident,true));if(!$('world-journal').classList.contains('hidden'))$('world-journal-list').innerHTML=beats.slice(0,35).map(entryMarkup).join('')}
function renderPeople(){if(!world||!state)return;const query=$('people-search').value.toLowerCase();$('people-list').innerHTML=world.households.map(h=>{const members=state.actors.filter(a=>a.household_id===h.id&&`${a.name} ${h.address}`.toLowerCase().includes(query));if(!members.length)return '';return `<div class="household-label">${esc(h.address)}</div>${members.map(a=>`<button class="person-row" data-person="${a.id}"><img class="person-avatar person-photo" src="${portraitUrl(a.appearance,54,64)}" alt="" width="32" height="34"><span><strong>${esc(a.name)}</strong><small>${esc(a.action?.label||'Taking a moment')}</small></span>${icon('arrow')}</button>`).join('')}`}).join('')||'<p class="empty-note">No neighbors match that search.</p>';document.querySelectorAll('[data-person]').forEach(b=>b.onclick=async()=>{await selectPerson(b.dataset.person,true);$('people-drawer').classList.add('hidden')})}
function toggleDrawer(id){const opening=$(id).classList.contains('hidden');document.querySelectorAll('.drawer').forEach(d=>d.classList.add('hidden'));$(id).classList.toggle('hidden',!opening);if(id==='people-drawer'&&opening){renderPeople();$('people-search').focus()}if(id==='world-journal'&&opening)renderEvents()}
function download(filename,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
function toggleRoofs(){renderer.roofs={auto:'open',open:'closed',closed:'auto'}[renderer.roofs];$('roof-toggle').querySelector('span').textContent={auto:'Auto roofs',open:'Interiors',closed:'Roofs on'}[renderer.roofs];$('roof-toggle').classList.toggle('active',renderer.roofs!=='closed')}
function toggleGrid(){renderer.grid=!renderer.grid;$('grid-toggle').classList.toggle('active',renderer.grid)}
function bind(){
  $('pause').onclick=()=>control({paused:!state.paused});document.querySelectorAll('[data-speed]').forEach(b=>b.onclick=()=>control({speed:Number(b.dataset.speed)}));
  $('speed-select').onchange=event=>control({speed:Number(event.target.value)});
  $('objects-toggle').onclick=()=>objectExplorer.openList();
  $('save').onclick=async()=>{try{await api('/api/save',{});toast('Mosswood is saved. Their stories will be here when you return.')}catch(e){toast(e.message)}};
  $('zoom-in').onclick=()=>renderer.setZoom(renderer.camera.zoom*1.25);$('zoom-out').onclick=()=>renderer.setZoom(renderer.camera.zoom/1.25);$('fit').onclick=()=>renderer.fit();
  $('roof-toggle').onclick=toggleRoofs;$('grid-toggle').onclick=toggleGrid;
  $('follow').onclick=()=>{renderer.follow=!renderer.follow;if(renderer.follow)renderer.focusActor(selected,.95);renderHeading()};
  $('go-home').onclick=()=>{renderer.focusHome(person.home_id);renderHeading()};
  $('go-work').onclick=()=>{if(person.workplace?.building_id){renderer.focusHome(person.workplace.building_id);renderHeading()}};
  $('open-relationships').onclick=()=>openRelationships(person,state,id=>selectPerson(id,true));
  $('next-person').onclick=()=>{const i=state.actors.findIndex(a=>a.id===selected);selectPerson(state.actors[(i+1)%state.actors.length].id)};
  document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
  $('people-toggle').onclick=()=>toggleDrawer('people-drawer');$('journal-toggle').onclick=()=>toggleDrawer('world-journal');$('all-events').onclick=()=>toggleDrawer('world-journal');$('help-toggle').onclick=()=>toggleDrawer('help');$('explore').onclick=()=>{document.querySelectorAll('.drawer').forEach(d=>d.classList.add('hidden'));renderer.overview()};
  $('people-search').oninput=renderPeople;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).classList.add('hidden'));
  $('capture').onclick=()=>{const a=document.createElement('a');a.href=renderer.screenshot();a.download=`mosswood-day-${state.day}-${state.time.replace(':','')}.png`;a.click();toast('Neighborhood image captured.')};
  $('step-minute').onclick=async()=>{await control({paused:true});await control({step_seconds:60});await loadPerson();await loadEvents();toast('One minute of neighborhood life, with every event processed.')};
  window.addEventListener('keydown',e=>{if(e.defaultPrevented)return;if($('relationships-dialog')?.open){if(e.key==='Escape')closeRelationships();return}if(['INPUT','TEXTAREA','SELECT','BUTTON','A','SUMMARY'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();control({paused:!state.paused})}if(e.key.toLowerCase()==='g')toggleGrid();if(e.key.toLowerCase()==='r')toggleRoofs();if(e.key.toLowerCase()==='f')renderer.fit();if(e.key.toLowerCase()==='p')toggleDrawer('people-drawer');if(e.key==='+'||e.key==='=')renderer.setZoom(renderer.camera.zoom*1.15);if(e.key==='-')renderer.setZoom(renderer.camera.zoom/1.15);if(e.key==='Escape')document.querySelectorAll('.drawer').forEach(d=>d.classList.add('hidden'))});
}

async function main(){try{[world,state,rules]=await Promise.all([api('/api/world'),api('/api/state'),api('/api/rules')]);renderWorldIdentity();renderer=new NeighborhoodRenderer($('world'),$('minimap'),world,id=>selectPerson(id),async hid=>{const h=world.households.find(h=>h.id===hid);if(!h?.members?.length)return;await selectPerson(h.members[0]);renderer.focusHome(h.building_id)},id=>objectExplorer.openObject(id));objectExplorer=createObjectExplorer({world,getState:()=>state,rules,renderer,onActor:id=>selectPerson(id,true)});renderer.overview();connected=true;updateState(state);bind();await selectPerson(selected);await loadEvents();connect();
  window.mosswood={ready:true,get renderer(){return renderer},get state(){return state},get person(){return person},select:selectPerson,capture:()=>renderer.screenshot(),async configure(options={}){if(options.actor_id)await selectPerson(options.actor_id);if(options.tab)await setTab(options.tab);renderer.grid=!!options.grid;$('grid-toggle').classList.toggle('active',renderer.grid);if(options.building_id&&world.buildings.some(b=>b.id===options.building_id))renderer.focusHome(options.building_id);else if(options.view==='home')renderer.focusHome(person.home_id);else if(options.view==='follow'){renderer.focusActor(selected,1.4);renderer.follow=true}else if(options.view==='overview')renderer.overview();if(options.roofs){renderer.roofs=options.roofs;$('roof-toggle').querySelector('span').textContent={auto:'Auto roofs',open:'Interiors',closed:'Roofs on'}[options.roofs]}if(options.zoom)renderer.camera.zoom=options.zoom;if(options.overlay==='relationships')openRelationships(person,state,id=>selectPerson(id,true));else if(options.overlay===null)closeRelationships();await new Promise(requestAnimationFrame);renderer.render(performance.now());return {clock:state.clock,selected,zoom:renderer.camera.zoom}}};
  setInterval(()=>loadPerson(),1200);setInterval(()=>{loadEvents();if(!$('people-drawer').classList.contains('hidden'))renderPeople()},2500);
}catch(error){$('connection').textContent='Could not connect to the Python world';toast(error.message);console.error(error)}}
main();
