import {paintHouseFloor} from './generation-drawing.js';

const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cv=$('city-canvas'),ctx=cv.getContext('2d');
const state={city:null,session:null,selected:null,route:null,busy:false,unit:2,x:0,y:0,dpr:1,drag:null};
window.cityLab=state;
const colors={residential:'#91a988',civic:'#94a5a0',commercial:'#c5a984',leisure:'#ab91a5'};

function size(){const rect=cv.getBoundingClientRect();state.width=rect.width;state.height=rect.height;state.dpr=Math.min(devicePixelRatio||1,2);cv.width=Math.round(rect.width*state.dpr);cv.height=Math.round(rect.height*state.dpr);if(state.city)fit();else draw()}
function fit(){if(!state.city)return;state.unit=Math.min((state.width-46)/state.city.width,(state.height-46)/state.city.height);state.x=(state.width-state.city.width*state.unit)/2;state.y=(state.height-state.city.height*state.unit)/2;draw()}
function zoom(factor,px=state.width/2,py=state.height/2){const old=state.unit,next=Math.max(.65,Math.min(18,old*factor)),ratio=next/old;state.x=px+(state.x-px)*ratio;state.y=py+(state.y-py)*ratio;state.unit=next;draw()}
function fill(x,y,w,h,color){ctx.fillStyle=color;ctx.fillRect(x,y,w,h)}
function line(a,b,width,color){ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='square';ctx.stroke()}
function point(x,y){return [state.x+x*state.unit,state.y+y*state.unit]}
function draw(){ctx.setTransform(state.dpr,0,0,state.dpr,0,0);ctx.clearRect(0,0,state.width,state.height);const city=state.city;if(!city)return;const u=state.unit;fill(state.x,state.y,city.width*u,city.height*u,'#dce9d0');
  for(const land of city.landscapes){const [x,y,w,h]=land.bounds,[px,py]=point(x,y);fill(px,py,w*u,h*u,land.zone==='park'?'#b4cb9d':'#8ab4b7');if(land.zone==='park'){for(let k=0;k<8;k++){const xx=px+(3+(k%4)*w/5)*u,yy=py+(4+Math.floor(k/4)*h/2.5)*u;fill(xx,yy,Math.max(2,2*u),Math.max(2,2*u),'#789b6d')}}else{for(let k=0;k<3;k++)line([px+4*u,py+(5+k*5)*u],[px+(w-4)*u,py+(5+k*5)*u],Math.max(1,u*.35),'#b6d1c8')}}
  for(const plot of city.plots){const [x,y,w,h]=plot.bounds,[px,py]=point(x,y);fill(px,py,w*u,h*u,plot.zone==='residential'?'#cdddbd':'#e0e3ce');ctx.strokeStyle='#f6f4df';ctx.lineWidth=Math.max(1,u*.3);ctx.strokeRect(px,py,w*u,h*u)}
  for(const edge of city.edges){const a=point(...edge.a),b=point(...edge.b),wide=edge.class==='arterial'?5.7:edge.class==='local'?3.2:1.8;line(a,b,wide*u,edge.class==='pedestrian'?'#e7d8a9':'#e9e4cc');if(edge.class!=='pedestrian'){line(a,b,(wide-1.1)*u,edge.class==='arterial'?'#9d9b85':'#c0ba9e');if(edge.class==='arterial'&&u>1.6){ctx.setLineDash([3*u,4*u]);line(a,b,Math.max(1,u*.14),'#ede6cb');ctx.setLineDash([])}}}
  for(const plot of city.plots){const [x,y,w,h]=plot.building_bounds,[px,py]=point(x,y);line(point(...plot.frontage),point(...plot.door),Math.max(2,1.4*u),'#ead9b0');fill(px+u*.25,py+u*.4,w*u,h*u,'#546d5130');fill(px,py,w*u,h*u,colors[plot.zone]);fill(px+u,py+u,(w-2)*u,(h-2)*u,plot.zone==='residential'?'#b7c4a2':'#d4d2b7');ctx.strokeStyle=plot.id===state.selected?'#3b735f':'#f5f0d8';ctx.lineWidth=plot.id===state.selected?Math.max(2,u*.85):Math.max(1,u*.35);ctx.strokeRect(px,py,w*u,h*u);fill(...point(...plot.door),Math.max(2,u),Math.max(2,u),'#f6e7bb');if(u>1.4){ctx.textAlign='center';ctx.fillStyle='#334f42';ctx.font=`${Math.max(9,Math.min(14,u*2.5))}px Segoe UI`;ctx.fillText(plot.name,px+w*u/2,py+h*u/2)}}
  if(state.route){const cells=state.route.public_path;ctx.beginPath();cells.forEach(([x,y],i)=>{const p=point(x+.5,y+.5);ctx[i?'lineTo':'moveTo'](...p)});ctx.strokeStyle='#b15b71';ctx.lineWidth=Math.max(2,1.2*u);ctx.stroke()}
}
function inspect(){const city=state.city;if(!city)return;const plot=city.plots.find(p=>p.id===state.selected);if(!plot){$('inspector').innerHTML=`<h2>Ein Grundstück wählen</h2><p>${city.plots.length} Gebäude und ${city.landscapes.length} Grün- oder Wasserblöcke. Klicke auf einen bebauten Block.</p><p class="hint">Alle ${city.validation.connected_entrances} Eingänge sind vom öffentlichen Netz erreichbar.</p>`;return}
  const rooms=plot.design.floors.flatMap(f=>f.rooms.map(r=>({floor:f.name,room:r})));$('inspector').innerHTML=`<h2>${esc(plot.name)}</h2><span class="pill">${esc(plot.zone)}</span>${plot.program_fallback?'<span class="pill">Raumprogramm als Prototyp</span>':''}<dl><dt>Grundstück</dt><dd>${plot.bounds[2]} × ${plot.bounds[3]} m</dd><dt>Gebäude</dt><dd>${plot.building_bounds[2]} × ${plot.building_bounds[3]} m</dd><dt>Räume</dt><dd>${rooms.length}</dd><dt>Arbeitsplätze an Möbeln</dt><dd>${plot.capacity.jobs}</dd><dt>Büroeinheiten</dt><dd>${plot.capacity.office_units}</dd><dt>Ausgestattete Plätze</dt><dd>${plot.capacity.equipped_places}</dd>${plot.capacity.students?`<dt>Schülerplätze</dt><dd>${plot.capacity.students}</dd>`:''}<dt>Flächenschätzung</dt><dd>${plot.capacity.area_based_occupant_estimate} Personen</dd></dl><p class="hint">Arbeitsplätze und ausgestattete Plätze zählen erzeugte Möbel. Die Flächenschätzung ist keine Sitzplatzzahl.</p><canvas class="room-preview" id="preview" width="360" height="225" aria-label="Gebäudegrundriss"></canvas><h3>Weg bis zum Raum</h3><select id="target-room">${rooms.map(({floor,room})=>`<option value="${esc(room.id)}">${esc(floor)} · ${esc(room.name)}</option>`).join('')}</select><button id="route">Öffentlichen Weg prüfen</button><p id="route-status">Vom Straßennetz durch die Haustür zum Zimmer.</p>`;
  const preview=$('preview'),c=preview.getContext('2d'),d=plot.design,unit=Math.min(342/d.width,205/d.height);c.fillStyle='#e5eddd';c.fillRect(0,0,360,225);paintHouseFloor(c,d,d.ground_floor_index||0,(360-d.width*unit)/2,(225-d.height*unit)/2,unit,{labels:false});$('route').onclick=()=>routeTo(plot)}
async function routeTo(plot){try{const roomId=$('target-room').value;const response=await fetch(`/api/generation/city/${state.session}/route`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plot_id:plot.id,room_id:roomId})});const result=await response.json();if(!response.ok)throw Error(result.detail||'Route konnte nicht berechnet werden');state.route=result;$('route-status').textContent=`${result.public_path.length-1} öffentliche Schritte + ${result.interior_route.steps.length} Innenschritte · ${result.seconds_without_queue} s ohne Warteschlange.`;draw()}catch(error){$('route-status').textContent=error.message}}
async function generate(){if(state.busy)return;state.busy=true;$('generate').disabled=true;$('error').hidden=true;try{const brief={seed:+$('seed').value,columns:+$('columns').value,rows:+$('rows').value};const response=await fetch('/api/generation/city',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(brief)});const result=await response.json();if(!response.ok)throw Error(result.detail||'Stadtteil konnte nicht erzeugt werden');state.city=result.design;state.session=result.session_id;state.selected=null;state.route=null;$('title').textContent=`${brief.columns} × ${brief.rows} Blöcke · Seed ${brief.seed}`;$('badge').textContent='✓ Straßen und Eingänge verbunden';$('caption').textContent=`${state.city.width} × ${state.city.height} m Planungsrahmen · ${state.city.city_version}`;$('metrics').innerHTML=`<div><b>${state.city.validation.buildings}</b><span>GEPRÜFTE GEBÄUDE</span></div><div><b>${state.city.validation.services.length}</b><span>DIENSTE</span></div><div><b>${state.city.validation.jobs}</b><span>ARBEITSPLÄTZE AN MÖBELN</span></div>`;fit();inspect()}catch(error){$('error').hidden=false;$('error').textContent=error.message}finally{state.busy=false;$('generate').disabled=false}}
cv.onpointerdown=event=>{cv.setPointerCapture(event.pointerId);state.drag={x:event.clientX,y:event.clientY,ox:state.x,oy:state.y,moved:false}};
cv.onpointermove=event=>{if(!state.drag)return;const dx=event.clientX-state.drag.x,dy=event.clientY-state.drag.y;if(Math.abs(dx)+Math.abs(dy)>4)state.drag.moved=true;state.x=state.drag.ox+dx;state.y=state.drag.oy+dy;draw()};
cv.onpointerup=event=>{if(state.drag&&!state.drag.moved&&state.city){const box=cv.getBoundingClientRect(),x=(event.clientX-box.left-state.x)/state.unit,y=(event.clientY-box.top-state.y)/state.unit;state.selected=state.city.plots.find(plot=>{const [px,py,pw,ph]=plot.bounds;return px<=x&&x<px+pw&&py<=y&&y<py+ph})?.id||null;state.route=null;inspect();draw()}state.drag=null};cv.onpointercancel=()=>state.drag=null;
cv.addEventListener('wheel',event=>{event.preventDefault();const box=cv.getBoundingClientRect();zoom(Math.exp(-event.deltaY*.0015),event.clientX-box.left,event.clientY-box.top)},{passive:false});
$('generate').onclick=generate;$('fit').onclick=fit;$('zoom-in').onclick=()=>zoom(1.3);$('zoom-out').onclick=()=>zoom(1/1.3);new ResizeObserver(size).observe(cv);generate();
