import {paintHouseFloor,paintRoom} from './generation-drawing.js';
import {drawPerson} from './renderer.js';

const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const s={tab:'building',design:null,session:null,demo:null,floor:0,selected:null,ready:false,busy:false,camera:{unit:15,x:0,y:0},regionSession:null,route:null,job:null};
window.workshop=s;
const cv=$('canvas'),c=cv.getContext('2d');let catalog,timer,drag;
const zones={residential:'#c4d2aa',civic:'#d2c7a9',commercial:'#cfbdab',industrial:'#b7c4bf',park:'#afc396',water:'#91b8b3'};
const states={queued:'Eingeplant',discovering:'Lücke suchen',drafting:'Entwurf bauen',validating:'Prüfen',awaiting_review:'Sichtprüfung offen',published:'Freigegeben',rejected:'Abgelehnt',failed:'Fehlgeschlagen',cancelled:'Abgebrochen'};
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:JSON.stringify(d.detail));return d}
function tell(message){$('message').textContent=message;$('message').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('message').hidden=true,9000)}
function floorName(n){const e=s.design?.floors?.[n]?.elevation??n;return e<0?'UG':e===0?'EG':`${e}. OG`}
function size(){const b=cv.getBoundingClientRect();s.width=b.width;s.height=b.height;s.dpr=Math.min(devicePixelRatio||1,2);cv.width=Math.round(b.width*s.dpr);cv.height=Math.round(b.height*s.dpr);draw()}
function origin(){const d=s.design;return {x:(s.width-d.width*s.camera.unit)/2+s.camera.x,y:(s.height-d.height*s.camera.unit)/2+s.camera.y}}
function fit(){if(!s.design)return;s.camera={unit:Math.min((s.width-55)/s.design.width,(s.height-105)/s.design.height),x:0,y:7};draw()}
function zoom(factor,px=s.width/2,py=s.height/2){const old=s.camera.unit,next=Math.max(1,Math.min(120,old*factor)),r=next/old;s.camera={unit:next,x:(s.camera.x-(px-s.width/2))*r+(px-s.width/2),y:(s.camera.y-(py-s.height/2))*r+(py-s.height/2)};draw()}
function paintRegion(d,x,y,u){
  c.fillStyle='#c6d1af';c.fillRect(x,y,d.width*u,d.height*u);
  for(const e of d.edges){c.lineCap='square';c.lineWidth=10*u;c.strokeStyle='#e8dec1';c.beginPath();c.moveTo(x+e.a[0]*u,y+e.a[1]*u);c.lineTo(x+e.b[0]*u,y+e.b[1]*u);c.stroke();c.lineWidth=6*u;c.strokeStyle='#aea995';c.stroke();c.lineWidth=.23*u;c.strokeStyle='#e9ddba';c.setLineDash([3*u,3*u]);c.stroke();c.setLineDash([])}
  for(const l of d.landscapes){const [px,py,pw,ph]=l.bounds;c.fillStyle=zones[l.zone];c.fillRect(x+px*u,y+py*u,pw*u,ph*u);if(l.zone==='park'){for(let i=0;i<6;i++){const tx=px+4+(i%3)*12,ty=py+4+Math.floor(i/3)*16;c.fillStyle='#72935e';c.fillRect(x+tx*u,y+ty*u,5*u,5*u);c.fillStyle='#9db57d';c.fillRect(x+(tx+1)*u,y+(ty-1)*u,5*u,4*u)}}else{c.strokeStyle='#bdd4c5';c.lineWidth=u;for(let k=0;k<4;k++){c.beginPath();c.moveTo(x+(px+7)*u,y+(py+6+k*6)*u);c.lineTo(x+(px+pw-7)*u,y+(py+6+k*6)*u);c.stroke()}}c.fillStyle='#496d55';c.font=`${Math.max(10,u*2)}px Segoe UI`;c.textAlign='center';c.fillText(l.name,x+(px+pw/2)*u,y+(py+ph/2)*u)}
  for(const p of d.plots){const[px,py,pw,ph]=p.bounds;c.fillStyle=zones[p.zone];c.fillRect(x+px*u,y+py*u,pw*u,ph*u);c.strokeStyle='#f5f0da';c.lineWidth=1;c.strokeRect(x+px*u,y+py*u,pw*u,ph*u);c.fillStyle='#dec9a1';for(const[xx,yy]of p.footpath)c.fillRect(x+xx*u,y+yy*u,u,u);const[bx,by]=p.building_bounds;paintHouseFloor(c,p.design,p.design.ground_floor_index,x+bx*u,y+by*u,u,{labels:false});if(p.id===s.selected){c.strokeStyle='#49776d';c.lineWidth=3;c.strokeRect(x+px*u,y+py*u,pw*u,ph*u)}if($('labels').checked){c.fillStyle='#3f6450';c.font=`${Math.max(9,Math.min(13,u*2))}px Segoe UI`;c.textAlign='center';c.fillText(p.name,x+(px+pw/2)*u,y+(py+ph+2)*u)}}
  if(s.route){c.strokeStyle='#a97795';c.lineWidth=Math.max(2,u*.7);c.beginPath();s.route.public_path.forEach(([xx,yy],i)=>c[i?'lineTo':'moveTo'](x+(xx+.5)*u,y+(yy+.5)*u));c.stroke()}
}
function draw(){c.setTransform(s.dpr,0,0,s.dpr,0,0);c.clearRect(0,0,s.width,s.height);c.imageSmoothingEnabled=false;if(!s.design||s.tab==='factory')return;const{x,y}=origin(),u=s.camera.unit;if(s.tab==='region')paintRegion(s.design,x,y,u);else{paintHouseFloor(c,s.design,s.floor,x,y,u,{overlay:$('clearance').checked,labels:$('labels').checked,selected:s.selected});for(const a of s.demo?.actors||[]){if(a.position?.[0]===s.floor)drawPerson(c,a.appearance,x+(a.position[1]+.5)*u,y+(a.position[2]+.85)*u,{scale:u/32,walking:false});else if(a.ride?.from?.[0]===s.floor){c.fillStyle='#487362';c.fillRect(x+a.ride.from[1]*u,y+a.ride.from[2]*u,u*.7,u*.7)}}}}
function floors(){ $('floors').innerHTML=s.tab==='region'?'':s.design.floors.map(f=>`<button class="${f.level===s.floor?'active':''}" data-floor="${f.level}">${floorName(f.level)}</button>`).join('');$('floors').querySelectorAll('button').forEach(b=>b.onclick=()=>{s.floor=+b.dataset.floor;s.selected=null;floors();inspect();draw()})}
function inspect(){if(!s.design)return;const d=s.design;let html='';if(s.tab==='region'){
  html=`<h3>Ein verbundenes Quartier.</h3><p>${d.validation.instantiated_buildings} ausgebaute Gebäude · ${d.validation.rooms} Räume.</p><ul><li>Öffentliches Wegenetz verbunden</li><li>Jede Haustür angeschlossen</li><li>Innenräume separat vollständig geprüft</li></ul>`;
  const p=d.plots.find(p=>p.id===s.selected);if(p){html+=`<div class="object-card"><h3>${esc(p.name)}</h3><p>${p.design.width} × ${p.design.height} m · ${p.design.levels} Etagen</p><button class="quiet" id="open-building">Gebäude öffnen →</button><label>Zielraum<select id="region-target">${p.design.floors.flatMap(f=>f.rooms.map(r=>`<option value="${esc(r.id)}">${esc(f.name)} · ${esc(r.name)}</option>`)).join('')}</select></label><button class="quiet" id="region-route">Vom Quartierseingang dorthin</button><p id="route-result">${s.route?`${s.route.public_path.length} öffentliche Wegzellen + ${s.route.interior_route.steps.length} Gebäudeschritte.`:''}</p></div>`}else html+='<p class="hint">Ein Grundstück anklicken: Grundriss öffnen oder einen Weg bis zum Zimmer berechnen.</p>';
  html+=`<details><summary>Grenzen dieses Prototyps</summary><ul>${d.limitations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></details>`;$('inspector').innerHTML=html;if(p){$('open-building').onclick=async()=>{try{const result=await api('/api/generation/building',p.request);setTab('building',false);loadBuilding(result);$('building-template').value='family';tell('Gebäude aus dem Quartier geöffnet. Formularwerte gelten erst für einen neuen Entwurf.')}catch(e){tell(e.message)}};$('region-route').onclick=async()=>{try{s.route=await api(`/api/generation/region/${s.regionSession}/route`,{plot_id:p.id,room_id:$('region-target').value});$('route-result').textContent=`${s.route.public_path.length} öffentliche Wegzellen + ${s.route.interior_route.steps.length} Gebäudeschritte. Übergang an der Haustür geprüft.`;draw()}catch(e){tell(e.message)}}}return;
  }
  const v=d.validation,cap=v.sleep_capacity,unused=v.footprint_coverage?.floors?.[s.floor]?.unassigned_cells;html=`<h3>${esc(d.floors[s.floor].name)}</h3><dl><dt>Planungsrahmen</dt><dd>${d.width} × ${d.height} m</dd><dt>Zimmer</dt><dd>${v.room_count??d.floors.reduce((n,f)=>n+f.rooms.length,0)}</dd><dt>Etagen gesamt</dt><dd>${d.levels}</dd>${cap?.required?`<dt>Schlafplätze</dt><dd>${cap.provided} / ${cap.required} benötigt</dd>`:''}${v.student_capacity?`<dt>Schülerplätze</dt><dd>${v.student_capacity} mit Tisch und Stuhl</dd>`:''}${unused!=null?`<dt>Nicht ausgebaut</dt><dd>${unused} m² auf dieser Etage</dd>`:''}</dl><p class="hint">Raummaße sind Rasterflächen; grüne Zellen im Rahmen sind nicht bebaut.</p><ul><li>Räume vom Eingang erreichbar</li><li>Bedienflächen bleiben frei</li><li>Treppen und Aufzug zeitgebunden</li></ul>`;
  const o=d.floors[s.floor].objects.find(o=>o.id===s.selected);if(o){const actions=catalog.affordances.objects[o.kind]||[];html+=`<div class="object-card"><div class="eyebrow">OBJEKTVERTRAG</div><h3>${esc(o.name)}</h3><p>${o.w} × ${o.h} m · ${o.clearance.length} Bedienfelder</p>${catalog.bed_capacities[o.kind]?`<p>${catalog.bed_capacities[o.kind]} Schlafplatz/-plätze</p>`:''}${actions.map(k=>`<span class="pill">${esc(catalog.affordances.actions[k]?.name||k)}</span>`).join('')}<p class="hint">Aktionsvorlagen, noch keine zusätzlich ausgeführten Hauptwelt-Aktionen.</p></div>`}else html+='<p class="hint">Möbel anklicken, um Maße, Schlafplätze und mögliche Aktionen zu sehen.</p>';
  html+=`<details open><summary>Räume auf dieser Etage</summary><ul>${d.floors[s.floor].rooms.map(r=>`<li>${esc(r.name)} · ${r.width} × ${r.height} m · ${r.width*r.height} m² Rasterfläche${r.capacity?.students?` · ${r.capacity.students} echte Schülerplätze`:''}</li>`).join('')}</ul></details><details><summary>Planungsprotokoll</summary><ul>${d.trace.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></details>`;$('inspector').innerHTML=html;
}
function loadBuilding(result){s.design=result.design;s.session=result.session_id;s.demo=result.demo;s.floor=s.design.ground_floor_index||0;s.selected=null;s.route=null;$('design-title').textContent=s.design.name;$('badge').textContent='✓ Geometrie geprüft';$('badge').classList.remove('bad');$('caption').textContent=`${s.design.width} × ${s.design.height} m · ${s.design.levels} Etagen · Seed ${s.design.seed} · Version ${s.design.generator_version}`;$('walk-controls').hidden=false;$('walk-status').textContent='Drei unabhängige Wegprüfer';floors();inspect();fit();s.ready=true}
async function generate(){if(s.busy)return;s.busy=true;s.ready=false;$('generate').disabled=true;try{const seed=+$('seed').value;if(s.tab==='region'){const result=await api('/api/generation/region',{seed,columns:+$('r-columns').value,rows:+$('r-rows').value});s.design=result.design;s.regionSession=result.session_id;s.selected=null;s.route=null;s.demo=null;$('design-title').textContent='Die Nachbarschaft von innen.';$('badge').textContent='✓ Eingänge verbunden';$('badge').classList.remove('bad');$('caption').textContent=`${s.design.width} × ${s.design.height} m · ${s.design.plots.length} ausgebaute Gebäude · Seed ${seed}`;$('walk-controls').hidden=true;floors();inspect();fit();s.ready=true}else{const type=$('building-template').value;const body={seed,width:+$('b-width').value,depth:+$('b-depth').value,room_count:+$('b-rooms').value,levels_above_ground:+$('b-levels').value,basements:+$('b-basement').checked,elevator:$('b-lift').checked,terrace_exit:$('b-terrace').checked,residents:type==='family'?{adults:+$('b-adults').value,children:+$('b-children').value,teens:+$('b-teens').value}:{adults:0,children:0,teens:0}};if(type!=='family')body.room_program=catalog.building_templates[type].room_program;loadBuilding(await api('/api/generation/building',body))}}catch(e){tell(e.message);$('badge').textContent='Auftrag nicht erfüllbar';$('badge').classList.add('bad');s.ready=!!s.design}finally{s.busy=false;$('generate').disabled=false}}
function setTab(tab,regenerate=true){if(s.busy)return;s.tab=tab;s.design=null;s.ready=false;s.selected=null;s.route=null;document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-selected',b.dataset.tab===tab)});$('design-panel').hidden=tab==='factory';$('factory-panel').hidden=tab!=='factory';$('building-fields').hidden=tab!=='building';$('region-fields').hidden=tab!=='region';$('design-kicker').textContent=tab==='region'?'ZONEN → GRUNDSTÜCKE → INNENRÄUME':'PARAMETRISCHER GRUNDRISS';if(tab==='factory'){refreshJobs();return}size();if(regenerate)generate()}
function template(){const type=$('building-template').value;$('residents-fields').hidden=type!=='family';if(type==='family'){$('b-width').value=18;$('b-depth').value=19;$('b-rooms').value=6;$('b-levels').value=2}else{$('b-width').value=type==='school'?36:29;$('b-depth').value=type==='school'?30:27;$('b-rooms').value=catalog.building_templates[type].room_program.length;$('b-levels').value=1;$('b-basement').checked=false}}
async function refreshJobs(){try{const data=await api('/api/workshop/jobs');$('jobs').innerHTML=data.jobs.map(j=>`<button class="job ${j.id===s.job?'selected':''}" data-job="${esc(j.id)}"><span>${esc(j.focus)}<small>${esc(j.provider)} · ${esc(j.model)}</small></span><span class="job-state">${esc(states[j.state]||j.state)}</span></button>`).join('')||'<p class="hint">Noch keine Werkstatt-Aufträge. Die oben genannte Codex-Entwicklungsrunde ist separat dokumentiert.</p>';$('jobs').querySelectorAll('[data-job]').forEach(b=>b.onclick=()=>showJob(b.dataset.job))}catch(e){tell(e.message)}}
async function showJob(id){try{s.job=id;const j=await api('/api/workshop/jobs/'+id);const report=j.report;$('job-detail').innerHTML=`<h3>${esc(j.proposal?.title||j.focus)}</h3><p>${esc(j.proposal?.rationale||j.error||'Noch kein Entwurf.')}</p>${report?`<p><b>${report.valid?'Technisch bestanden':'Technisch abgelehnt'}</b> · ${report.room_checks} Raumprüfungen · ${report.building_checks} Gebäudeprüfungen</p>${report.errors.length?`<pre>${esc(report.errors.join('\n'))}</pre>`:''}${report.previews.map((_,i)=>`<canvas class="preview" data-preview="${i}" width="700" height="340" aria-label="Prüfentwurf des neuen Raumtyps"></canvas>`).join('')}`:''}<div>${j.events.map(e=>`<div class="event"><b>${esc(states[e.state]||e.state)}</b><span>${esc(e.message)}</span></div>`).join('')}</div>${j.state==='awaiting_review'?'<label class="check"><input id="reviewed" type="checkbox"> Grafik und Raumentwurf angesehen</label><button id="publish" class="primary">Diesen Entwurf freigeben</button>':''}${j.state==='published'?'<p>✓ Versioniert in der Werkstatt-Bibliothek. Die Hauptwelt wurde nicht geändert.</p>':''}`;
  $('job-detail').querySelectorAll('[data-preview]').forEach(el=>{const room=report.previews[+el.dataset.preview],ctx=el.getContext('2d'),u=Math.min(580/(room.width+1),280/(room.height+1));ctx.imageSmoothingEnabled=false;paintRoom(ctx,room,(el.width-room.width*u)/2,(el.height-room.height*u)/2,u,{overlay:true})});if($('publish'))$('publish').onclick=async()=>{if(!$('reviewed').checked){tell('Bitte zuerst Grafik und Raum prüfen und die Sichtprüfung bestätigen.');return}try{await api(`/api/workshop/jobs/${id}/publish`,{reviewer:'Lokaler Nutzer',visual_reviewed:true,expected_pack_hash:report.pack_hash});await refreshJobs();await showJob(id)}catch(e){tell(e.message)}};await refreshJobs()}catch(e){tell(e.message)}}
$('demo-run').onclick=async()=>{$('demo-run').disabled=true;try{const result=await api('/api/workshop/demo',{});await showJob(result.jobs[0].id)}catch(e){tell(e.message)}finally{$('demo-run').disabled=false}};
$('refresh-jobs').onclick=refreshJobs;$('generate').onclick=generate;$('building-template').onchange=template;$('clearance').onchange=draw;$('labels').onchange=draw;$('fit').onclick=fit;$('zoom-in').onclick=()=>zoom(1.3);$('zoom-out').onclick=()=>zoom(1/1.3);
$('step').onclick=async()=>{if(!s.session||s.busy)return;try{s.demo=await api(`/api/generation/demo/${s.session}/advance`,{seconds:30});$('walk-status').textContent=`${s.demo.clock} s · ${s.demo.metrics.arrivals} Ziele erreicht · ${s.demo.metrics.stairs_trips} Treppen / ${s.demo.metrics.elevator_trips} Liftfahrten`;if(s.demo.invariant_errors.length)throw Error(s.demo.invariant_errors.join(', '));draw()}catch(e){tell(e.message)}};
$('export').onclick=()=>{if(!s.design)return;const url=URL.createObjectURL(new Blob([JSON.stringify(s.design,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`mosswood-${s.design.kind}-${s.design.seed}.json`;a.click();URL.revokeObjectURL(url)};
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));cv.addEventListener('wheel',e=>{e.preventDefault();const b=cv.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-b.x,e.clientY-b.y)},{passive:false});cv.onpointerdown=e=>{cv.setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,cx:s.camera.x,cy:s.camera.y,moved:false}};cv.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)>5)drag.moved=true;s.camera.x=drag.cx+dx;s.camera.y=drag.cy+dy;draw()};cv.onpointerup=e=>{if(drag&&!drag.moved&&s.design){const b=cv.getBoundingClientRect(),{x,y}=origin(),px=(e.clientX-b.x-x)/s.camera.unit,py=(e.clientY-b.y-y)/s.camera.unit;if(s.tab==='region'){s.selected=s.design.plots.find(p=>px>=p.bounds[0]&&py>=p.bounds[1]&&px<p.bounds[0]+p.bounds[2]&&py<p.bounds[1]+p.bounds[3])?.id;s.route=null}else s.selected=s.design.floors[s.floor].objects.find(o=>px>=o.x&&py>=o.y&&px<o.x+o.w&&py<o.y+o.h)?.id;inspect();draw()}drag=null};cv.onpointercancel=()=>drag=null;cv.onkeydown=e=>{if(s.tab!=='building'||!s.design)return;if(e.key==='PageUp'||e.key==='PageDown'){e.preventDefault();s.floor=Math.max(0,Math.min(s.design.levels-1,s.floor+(e.key==='PageUp'?1:-1)));floors();inspect();draw()}};
// A previous brief's warning must not follow the user into a new task/view.
document.addEventListener('click', e => {
  if (!s.busy && e.target.closest('[data-tab], #generate')) {
    clearTimeout(timer); $('message').hidden = true;
  }
}, true);
new ResizeObserver(size).observe(cv);s.generate=generate;s.setTab=setTab;s.showJob=showJob;s.draw=draw;
try{catalog=await api('/api/generation/catalog');s.catalog=catalog;$('stats').innerHTML=`<div><b>${Object.keys(catalog.rooms).length}</b><span>RAUMTYPEN</span></div><div><b>${Object.keys(catalog.objects).length}</b><span>GEGENSTÄNDE</span></div><div><b>${Object.keys(catalog.building_templates).length}</b><span>ÖFFENTLICHE PROFILE</span></div>`;$('taxonomy').innerHTML=`<div class="taxonomy-grid">${catalog.public_building_backlog.map(t=>`<article><strong>${esc(t.name||t.building)}</strong><span class="pill">${t.status==='planned'?'Geplant':'Prototyp'}</span><p>${t.rooms.map(esc).join(' · ')}</p><p>${t.objects.map(esc).join(', ')}</p></article>`).join('')}</div>`;template();size();await generate()}catch(e){tell(e.message)}
